name: Build NTRGhidra

on:
  push:
    branches:
      - '**'  # build on every commit
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JDK_VERSION }}
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Setup Ghidra
        uses: antoniovazquezblanco/setup-ghidra@v2.0.19
        with:
          version: ${{ vars.GHIDRA_BUILD_VERSION }}

      - name: Build
        run: gradle

      # Upload artifacts to GitHub Actions for every build
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NTRGhidra-build
          path: dist/ghidra_*_NTRGhidra.zip

      # Upload to GitHub Release only when a release is created
      - name: Release
        if: github.event_name == 'release'
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "dist/ghidra_*_NTRGhidra.zip"
          asset_name: "NTRGhidra.zip"
          asset_content_type: "application/zip"
